# Conichi Tech Challenge

### Prerequisites
* java-8 and set JAVA_HOME
* docker(optional)

### Running the application locally

Running with Docker:

```sh
$ ./mvnw clean install #creates jar file to create docker image
$ docker-compose up
```

Running without Docker:

```sh
$ ./mvnw spring-boot:run
```

Running tests From Terminal:

```sh
$ ./mvnw test
```

## Decision regarding Currency converter api:
* The currency conversion API given in the tech challenge for reference needs a license and free license allows only a limited number of calls(250) which I felt might not be sufficient for the application tetsing.Hence I chose a different service for this conversion. 

* Details:
API Reference: https://exchangeratesapi.io
API call used :https://api.exchangeratesapi.io/latest?base=EUR&symbols=INR

## Technologies
* used spring-boot for REST framework.
* use spring inbuilt cacheable option for caching.
* git for version control.

## API design
The app exposes three apis
* GET api For fetching current time `api/time`
* GET api for for converting a given amount from a base currency to a target currency `api/currency/convert` and it takes 3 paramaters `amount=10&baseCurrency=XXX&targetCurrency=YYY`
* GET api for providing country code based on a input VAT number. `api/vat/country` this api takes a paramater `vatNumber=XXX`

## Additional Changes Done:
* Used Swagger for autogenerated documentation, this can be verified from the given link once the application is running.
link to swagger : http://localhost:8081/swagger-ui.html#
* Used Docker and the details to run with docker are shared above and files are attached within the project
* Used spring-boot cacheable option for caching the api responses to avoid making frequent calls to external apis.This also saves time for requests. A time limit(TTL) of 20 minutes is set to reset the cache as the data in currency conversion api is frequently modified.This can be modified according to the nature of data being used.

## Example Tests and Results
1. `curl -X GET \
  'http://localhost:8081/api/currency/convert?amount=1&baseCurrency=INR&targetCurrency=EUR' `

* Output:
{
    "baseCurrency": "INR",
    "targetCurrency": "EUR",
    "baseAmount": 1,
    "targetAmount": 0.0126981708
}
2. `curl -X GET \
  'http://localhost:8081/api/vat/country?vatNumber=ATU00000024' `

* Output: 
{
    "isValid": false,
    "countryCode": "AT",
    "vatNumber": "U00000024"
}

3. `curl -X GET \
  http://localhost:8081/api/time `

* Output: {
    "currentTime": "2019-10-25T21:43:14.523+0000"
}

* It took 2-3 hours to finish the basic project and 1-2 hours more for the additional changes and end-to end testing.

## Improvements
* Caching for api requests is done through spring-boot supporting cacheable option. this can be replaced with options like redis instead and necessary results can be modified accordingly.
* Annotations like lombok can be used to avoid overriding of methods(equals , hashcode)  in reponse Objects.



